Repository yp2/ngx-cron-jobs, pull requests merged in 2022-10, with the labels that each got.

#56 Angular 14 upgrade
  .gitignore
  README.md
  angular.json
  package.json
  src/app/app.component.ts
  src/app/lib/cron-jobs/cron-jobs.component.spec.ts
  src/app/lib/cron-jobs/cron-jobs.component.ts
  src/tsconfig.app.json
  src/tsconfig.spec.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: hacktoberfest

#60 Update readme with more info for hacktoberfest
  README.md
Labels: hacktoberfest-accepted

#64 Angular 14 support - fixes for configuration files
  angular.json
  package.json
  public_api.ts
Labels: hacktoberfest, hacktoberfest-accepted

#65 tests(quartz-service): refactor to eliminate duplicate code
  src/app/lib/services/data.service.ts
  src/app/lib/services/posix.service.spec.ts
  src/app/lib/services/quartz.service.spec.ts
Labels: hacktoberfest, hacktoberfest-accepted
